# SPDX-FileCopyrightText: © 2026 James C. Womack
# SPDX-License-Identifier: CC0-1.0
version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - creds
  - docstrings
  - netham
  - pytest
  - rclone
  - venv
ignoreWords: []
import: []
language: en-GB
