# SPDX-FileCopyrightText: © 2026 James C. Womack
# SPDX-License-Identifier: MIT
FROM docker.io/library/ubuntu:24.04

# Unminimize Ubuntu minimal image, install useful packages for development 
RUN <<EOF
yes | unminimize
apt-get update && apt-get install --assume-yes --no-install-recommends \
  ca-certificates \
  curl \
  git \
  jq \
  language-pack-en \
  locales \
  less \
  openssl \
  man-db \
  make \
  rclone \
  reuse \
  tmux \
  vim \
  yq \
  unzip \
  zip
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

# Set UK English locale
ENV LANG=en_GB.utf8

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.10 /uv /uvx /bin/

# Create a standard user
RUN useradd --base-dir=/home --create-home --shell /bin/bash --user-group devuser

# Install AWS CLI
RUN <<EOF
TMPDIR=$(mktemp -d)
cd "${TMPDIR}"
curl -fsS "https://awscli.amazonaws.com/awscli-exe-linux-$(arch).zip" -o ./awscliv2.zip
unzip awscliv2.zip
./aws/install
rm -r "${TMPDIR}"
EOF

# Install Claude Code
RUN <<EOF
curl -fsSL https://downloads.claude.ai/keys/claude-code.asc -o /etc/apt/keyrings/claude-code.asc
echo "deb [signed-by=/etc/apt/keyrings/claude-code.asc] https://downloads.claude.ai/claude-code/apt/stable stable main" \
  | tee /etc/apt/sources.list.d/claude-code.list
apt-get update && apt-get install claude-code --assume-yes --no-install-recommends
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

# Switch to standard user
USER devuser

# Install Python from uv for user
RUN uv python install --default 3.14
