# SPDX-FileCopyrightText: © 2026 James C. Womack
# SPDX-License-Identifier: MIT
FROM docker.io/library/ubuntu:24.04

ARG TARGETARCH
ARG RCLONE_INSTALL_VERSION=v1.74.3

# Unminimize Ubuntu minimal image, install useful packages for development 
RUN <<EOF
yes | unminimize
apt-get update && apt-get install --assume-yes --no-install-recommends \
  ca-certificates \
  curl \
  dnsutils \
  git \
  gpg \
  iproute2 \
  jq \
  language-pack-en \
  locales \
  less \
  openssl \
  man-db \
  make \
  reuse \
  tmux \
  vim \
  yq \
  unzip \
  zip
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

# Set UK English locale
ENV LANG=en_GB.utf8

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.10 /uv /uvx /bin/

# Create a standard user
RUN useradd --base-dir=/home --create-home --shell /bin/bash --user-group devuser

# Install AWS CLI
RUN <<EOF
TMPDIR=$(mktemp -d)
cd "${TMPDIR}"
curl -fsS "https://awscli.amazonaws.com/awscli-exe-linux-$(arch).zip" -o ./awscliv2.zip
unzip awscliv2.zip
./aws/install
rm -r "${TMPDIR}"
EOF

# Install Claude Code
RUN <<EOF
curl -fsSL https://downloads.claude.ai/keys/claude-code.asc -o /etc/apt/keyrings/claude-code.asc
echo "deb [signed-by=/etc/apt/keyrings/claude-code.asc] https://downloads.claude.ai/claude-code/apt/stable stable main" \
  | tee /etc/apt/sources.list.d/claude-code.list
apt-get update && apt-get install --assume-yes --no-install-recommends claude-code
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

# Install recent rclone release, verifying against GPG-signed SHA256SUMS
# (rclone from Ubuntu 24.04 LTS repos is old (1.60) and has a bug where it will always send X-Amz-Acl headers that may
# not be accepted by some S3 storage where ACLs are disabled, e.g. VAST)
RUN --mount=type=tmpfs,dst=/build-tmp <<EOF 
cd /build-tmp
mkdir -v gnupg
chmod u=rwx,g=,o= gnupg
gpg --homedir=gnupg --list-keys
curl -sSL https://rclone.org/KEYS | gpg --homedir=gnupg --import
curl -sSLO https://downloads.rclone.org/${RCLONE_INSTALL_VERSION}/rclone-${RCLONE_INSTALL_VERSION}-linux-${TARGETARCH}.zip
curl -sSLO https://downloads.rclone.org/${RCLONE_INSTALL_VERSION}/SHA256SUMS
gpg --homedir=gnupg --verify SHA256SUMS && \
  sha256sum --ignore-missing -c SHA256SUMS && \
  unzip rclone-${RCLONE_INSTALL_VERSION}-linux-${TARGETARCH}.zip && \
  cp rclone-${RCLONE_INSTALL_VERSION}-linux-${TARGETARCH}/rclone /usr/local/bin/rclone && \
  chown root:root /usr/local/bin/rclone && \
  chmod u=rwx,g=rx,o=rx /usr/local/bin/rclone
EOF

# Switch to standard user
USER devuser

# Install Python from uv for user
RUN uv python install --default 3.14

